<a href="https://colab.research.google.com/github/Sofieagerbaek/NN.project.2021/blob/master/splitting_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
import torch


In [6]:
#Her indlæser jeg seq og val filerne og definere at jeg kun fremadrettet vil bruge de første 100 linjer
seq = pd.read_csv("seq.tsv", sep = "\t")
val = pd.read_csv("val.tsv", sep = "\t")

seq = seq.head(100)
val = val.head(100)

In [55]:
chr_vec = ['chr22','chr22','chr22']
start_vec = ['1','2','3']
stop_vec = ['1','2','3']
val_vec = ['11','30','87']
seq_vec = [('0,1,1,1,0'),('0,1,1,0,1'),('1,1,0,1,0')]

Final_list = np.array([chr_vec, start_vec, stop_vec, val_vec, seq_vec], dtype=object)
Final_list = np.transpose(Final_list)

df = pd.DataFrame(Final_list)

type(df)
print(df)

       0  1  2   3          4
0  chr22  1  1  11  0,1,1,1,0
1  chr22  2  2  30  0,1,1,0,1
2  chr22  3  3  87  1,1,0,1,0


In [54]:
df = tf.convert_to_tensor(df)

torch.save(df, "test.pt")

In [60]:
chr_vec = ['chr22','chr22','chr22','chr22',' chr22','chr22']
start_vec = ['1','2','3','4','5','6']
stop_vec = ['1','2','3','4','5','6']
val_vec = ['11','30','87','44','22','3']
seq_vec = [('0,1,1,1,0'),('0,1,1,0,1'),('1,1,0,1,0'),('0,1,1,1,0'),('0,1,1,0,1'),('1,1,0,1,0')]

Final_list = np.array([chr_vec, start_vec, stop_vec, val_vec, seq_vec], dtype=object)
Final_list = np.transpose(Final_list)

df = pd.DataFrame(Final_list)

In [63]:
train, test = train_test_split(df, test_size = 0.2)

test, val = train_test_split(test, test_size = 0.5)

print(train)
print(test)
print(val)

        0  1  2   3          4
1   chr22  2  2  30  0,1,1,0,1
2   chr22  3  3  87  1,1,0,1,0
0   chr22  1  1  11  0,1,1,1,0
4   chr22  5  5  22  0,1,1,0,1
       0  1  2  3          4
5  chr22  6  6  3  1,1,0,1,0
       0  1  2   3          4
3  chr22  4  4  44  0,1,1,1,0


In [7]:
#print(seq, val)
#train/test/val split 

seq_train, seq_val_test, val_train, val_val_test = train_test_split(seq, val, test_size = 0.1)

seq_val, seq_test, val_val, val_test = train_test_split(seq_val_test, val_val_test, test_size = 0.5)

In [8]:
#Tjekker om længden på de to er den samme (og 90% af 100)
print(len(seq_train), len(val_train))

90 90


In [45]:
print(seq_val)
type(seq_val)

    1  0  0.1  0.2  0.3  0.4  ...  0.598  0.599  1.200  0.600  0.601  0.602
5   1  0    0    0    0    0  ...    0.0    0.0    0.0    0.0    0.0    1.0
26  0  0    1    0    0    0  ...    0.0    0.0    0.0    0.0    0.0    1.0
10  0  0    0    1    0    0  ...    0.0    1.0    0.0    0.0    1.0    0.0
17  0  1    0    0    0    0  ...    0.0    0.0    0.0    0.0    1.0    0.0
66  0  0    0    1    1    0  ...    0.0    0.0    1.0    0.0    0.0    0.0

[5 rows x 804 columns]


pandas.core.frame.DataFrame

In [10]:
type(seq_train)
print(seq_train)

    1  0  0.1  0.2  0.3  0.4  ...  0.598  0.599  1.200  0.600  0.601  0.602
2   1  0    0    0    0    0  ...    0.0    0.0    1.0    0.0    0.0    0.0
13  1  0    0    0    1    0  ...    0.0    0.0    1.0    0.0    0.0    0.0
81  0  1    0    0    0    0  ...    0.0    0.0    0.0    1.0    0.0    0.0
48  0  0    0    1    0    1  ...    0.0    0.0    0.0    0.0    0.0    1.0
91  1  0    0    0    1    0  ...    0.0    0.0    1.0    0.0    0.0    0.0
.. .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
99  0  0    1    0    1    0  ...    0.0    1.0    1.0    0.0    0.0    0.0
70  1  0    0    0    0    0  ...    0.0    0.0    0.0    0.0    0.0    1.0
8   0  0    0    1    0    1  ...    0.0    0.0    0.0    0.0    1.0    0.0
83  0  0    0    1    0    0  ...    1.0    0.0    0.0    1.0    0.0    0.0
33  1  0    0    0    1    0  ...    0.0    0.0    1.0    0.0    0.0    0.0

[90 rows x 804 columns]


In [11]:
seqtrain = tf.convert_to_tensor(seq_train)


In [12]:
type(seqtrain)
print(seqtrain)

tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]], shape=(90, 804), dtype=float64)


In [15]:
torch.save(seqtrain, "seqtrain_tensor.pt")

In [17]:
t = torch.load("seqtrain_tensor.pt")
type(t)
print(t)

tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]], shape=(90, 804), dtype=float64)


In [ ]:
#Skriver tsv filer 

seq_train.to_csv("seq_train_few.tsv", sep="\t")
seq_val.to_csv("seq_val_few.tsv", sep="\t")
seq_test.to_csv("seq_test_few.tsv", sep="\t")
